{
 "title": "DNS",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "SHOW TAG VALUES FROM \"bind_counter\" WITH KEY = \"source\""
   }
  ]
 },
 "panels": [
  {
   "title": "Query response",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "SUCCESS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "QrySuccess" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "NXDOMAIN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "QryNXDOMAIN" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "FAILURE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "QryFailure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "NO DATA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "QryNxrrset" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "DUPLICATE",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "QryDuplicate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "SERVFAIL",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "QrySERVFAIL" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Query types",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "A" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "AAAA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "AAAA" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "CNAME",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "CNAME" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "PTR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "PTR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "NS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "NS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "MX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "MX" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "TXT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "TXT" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "SRV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "SRV" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "SOA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "SOA" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "NAPTR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "NAPTR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "AXFR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "AXFR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ANY",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "ANY" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "IXFR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "IXFR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "HINFO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "HINFO" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "NOTIFY",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "NOTIFY" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Zone's transfers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "IXFRv4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "IXFRReqv4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "AXFRv4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "AXFRReqv4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "IXFRv6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "IXFRReqv6" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "AXFRv6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "AXFRReqv6" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xfr success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "XfrSuccess" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xfr failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "XfrFail" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "total_use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "bind_memory",
     "select": [
      [
       { "params": [ "total_use" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "block_size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "bind_memory",
     "select": [
      [
       { "params": [ "block_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "in_use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "bind_memory",
     "select": [
      [
       { "params": [ "in_use" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "context_size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "bind_memory",
     "select": [
      [
       { "params": [ "context_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "lost",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "bind_memory",
     "select": [
      [
       { "params": [ "lost" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Mismatch responses ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bind_counter",
     "select": [
      [
       { "params": [ "Mismatch" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "ya.ru's DNS query timings",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "8.8.8.8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "dns_query",
     "select": [
      [
       { "params": [ "query_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "8.8.8.8" },
      { "condition": "AND", "key": "domain", "operator": "=", "value": "ya.ru" }
     ]
    },
    {
     "alias": "1.1.1.1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "dns_query",
     "select": [
      [
       { "params": [ "query_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "1.1.1.1" },
      { "condition": "AND", "key": "domain", "operator": "=", "value": "ya.ru" }
     ]
    },
    {
     "alias": "$host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "dns_query",
     "select": [
      [
       { "params": [ "query_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "domain", "operator": "=", "value": "ya.ru" }
     ]
    }
   ]
  }
 ]
}